http:
  services:
    api:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:8091

  routers:
    api:
      entrypoints: ["web"]
      rule: "!PathPrefix(`/images`)"
      service: api

  middlewares:
    cors:
      headers:
        accessControlAllowCredentials: true
        accessControlAllowHeaders: "*"
        accessControlAllowMethods: "*"
        accessControlAllowOriginListRegex: '^https?://(localhost|127.0.0.1|192\.168\.\d+\.\d+)(:\d+)$'
        addVaryHeader: true
