version: "2.4"

services:
  # backend:
  #   build: .
  #   ports:
  #     - "8090:8090"
  #   volumes: 
  #     - "./config.yml:/go-commerce/config.yml"
  #   environment: 
  #     - "DATABASE_HOST=db"

  db:
    image: postgres:13-alpine
    environment:
      - "POSTGRES_USER=go_commerce"
      - "POSTGRES_PASSWORD=go_commerce"
    ports:
      - "5432:5432"
