services:
  e2e-selenium:
    image: docker.io/selenium/standalone-firefox:latest
    ports:
      - "127.0.0.1:4444:4444"
      - "127.0.0.1:7900:7900" # Password: secret
    shm_size: 2gb
    environment:
      TZ: Europe/Brussels

  e2e-db:
    image: docker.io/library/postgres:16-alpine
    environment:
      - "POSTGRES_USER=e2e"
      - "POSTGRES_PASSWORD=e2e"
    ports:
      - "127.0.0.1:5433:5432"
