services:
  e2e-selenium:
    image: docker.io/selenium/standalone-firefox:4.6
    ports:
      - "127.0.0.1:4444:4444"
      - "127.0.0.1:7900:7900" # Password: secret
    shm_size: 2gb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: Europe/Brussels

  e2e-db:
    image: docker.io/library/postgres:13-alpine # Keep in sync with GitHub Actions ("services" section)
    environment:
      - "POSTGRES_USER=e2e"
      - "POSTGRES_PASSWORD=e2e"
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - "./local/postgres-init-00-structure.sh:/docker-entrypoint-initdb.d/00-init-structure.sh"
