version: "2.4"

services:
  # backend:
  #   build: .
  #   ports:
  #     - "8090:8090"
  #   volumes:
  #     - "./config.yml:/go-commerce/config.yml"
  #   environment:
  #     - "DATABASE_HOST=db"

  db:
    image: postgres:13-alpine
    environment:
      - "POSTGRES_USER=go_commerce"
      - "POSTGRES_PASSWORD=go_commerce"
    ports:
      - "127.0.0.1:5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "127.0.0.1:8032:8080"
