x-defaults: &defaults
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  # Defined in local/traefik.yml
  # backend:
  #   build: .
  #   ports:
  #     - "8090:8090"
  #   volumes:
  #     - "./config.yml:/go-commerce/config.yml"
  #   environment:
  #     - "DATABASE_HOST=db"

  traefik:
    <<: *defaults
    image: traefik:latest
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.network=traefik"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/config"
      - "--entrypoints.web.address=:8090"
      - "--entrypoints.web.http.middlewares=cors@file"
      - "--entrypoints.traefik.address=:9000"
    ports:
      - "8090:8090"
      - "127.0.0.1:9000:9000"
    networks:
      - traefik
    volumes:
      - "./local/traefik.yml:/config/traefik.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  db:
    <<: *defaults
    image: postgres:13-alpine # Keep in sync with GitHub Actions ("services" section)
    environment:
      - "POSTGRES_USER=go_commerce"
      - "POSTGRES_PASSWORD=go_commerce"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "./local/postgres-init-00-structure.sh:/docker-entrypoint-initdb.d/00-init-structure.sh"
      - "./local/postgres-init-10-data.sh:/docker-entrypoint-initdb.d/10-init-data.sh"

  adminer:
    <<: *defaults
    image: adminer
    ports:
      - "127.0.0.1:8032:8080"

  imgproxy:
    <<: *defaults
    image: darthsim/imgproxy
    environment:
      - "IMGPROXY_KEY=8f2fd7184ad28abe1b2cd3b6bb0f74dff4765659260f72eff6bea4b9c065bb7d64cbe75e4cd89ca98693f6c24fd670d50b1556b1b307700c7bd4a7dc9e66a72d"
      - "IMGPROXY_SALT=efab808e2a395eb3032e7906bdc83efebe216a4fc05a833690b7f48b5f39c8ba78f651513beb08056510e71eeea951b9ce7fb50ce6dbac372ab1d8603d8ee9d4"
      - "IMGPROXY_LOCAL_FILESYSTEM_ROOT=/images"
      - "IMGPROXY_MAX_SRC_RESOLUTION=64"
    networks:
      - traefik
    volumes:
      - "./files/images:/images:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.images.entrypoints=web"
      - "traefik.http.routers.images.rule=PathPrefix(`/images`)"
      - "traefik.http.routers.images.middlewares=strip-images-prefix"
      - "traefik.http.middlewares.strip-images-prefix.stripPrefix.prefixes=/images"

  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0
    command:
      - "start-dev"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - keycloak
    ports:
      - 9001:8080
    depends_on:
      - keycloak-db

  # Update DB dump for init:
  # docker compose exec keycloak-db pg_dump -U keycloak --format custom keycloak > ./local/keycloak.pgdump
  keycloak-db:
    image: postgres:12-alpine
    networks:
      - keycloak
    environment:
      - "POSTGRES_USER=keycloak"
      - "POSTGRES_PASSWORD=keycloak"
      - "POSTGRES_DB=keycloak"
    volumes:
      - "./local/keycloak.pgdump:/init.pgdump:ro"
      - "./local/keycloak-db-restore.sh:/docker-entrypoint-initdb.d/restore.sh:ro"

# #################################################################
# #                            NETWORKS                           #
# #################################################################
networks:
  keycloak:
    name: keycloak

  traefik:
    name: traefik
