/*
GoCommerce

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResolvedServiceCategory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResolvedServiceCategory{}

// ResolvedServiceCategory struct for ResolvedServiceCategory
type ResolvedServiceCategory struct {
	// Compressed representation of ID
	Id string `json:"id"`
	Name string `json:"name"`
	// Should be sorted ascending by this column
	Order int64 `json:"order"`
	Services []Service `json:"services,omitempty"`
}

type _ResolvedServiceCategory ResolvedServiceCategory

// NewResolvedServiceCategory instantiates a new ResolvedServiceCategory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResolvedServiceCategory(id string, name string, order int64) *ResolvedServiceCategory {
	this := ResolvedServiceCategory{}
	this.Id = id
	this.Name = name
	this.Order = order
	return &this
}

// NewResolvedServiceCategoryWithDefaults instantiates a new ResolvedServiceCategory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResolvedServiceCategoryWithDefaults() *ResolvedServiceCategory {
	this := ResolvedServiceCategory{}
	return &this
}

// GetId returns the Id field value
func (o *ResolvedServiceCategory) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ResolvedServiceCategory) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ResolvedServiceCategory) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ResolvedServiceCategory) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ResolvedServiceCategory) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ResolvedServiceCategory) SetName(v string) {
	o.Name = v
}

// GetOrder returns the Order field value
func (o *ResolvedServiceCategory) GetOrder() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Order
}

// GetOrderOk returns a tuple with the Order field value
// and a boolean to check if the value has been set.
func (o *ResolvedServiceCategory) GetOrderOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Order, true
}

// SetOrder sets field value
func (o *ResolvedServiceCategory) SetOrder(v int64) {
	o.Order = v
}

// GetServices returns the Services field value if set, zero value otherwise.
func (o *ResolvedServiceCategory) GetServices() []Service {
	if o == nil || IsNil(o.Services) {
		var ret []Service
		return ret
	}
	return o.Services
}

// GetServicesOk returns a tuple with the Services field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResolvedServiceCategory) GetServicesOk() ([]Service, bool) {
	if o == nil || IsNil(o.Services) {
		return nil, false
	}
	return o.Services, true
}

// HasServices returns a boolean if a field has been set.
func (o *ResolvedServiceCategory) HasServices() bool {
	if o != nil && !IsNil(o.Services) {
		return true
	}

	return false
}

// SetServices gets a reference to the given []Service and assigns it to the Services field.
func (o *ResolvedServiceCategory) SetServices(v []Service) {
	o.Services = v
}

func (o ResolvedServiceCategory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResolvedServiceCategory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["order"] = o.Order
	if !IsNil(o.Services) {
		toSerialize["services"] = o.Services
	}
	return toSerialize, nil
}

func (o *ResolvedServiceCategory) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"order",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResolvedServiceCategory := _ResolvedServiceCategory{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResolvedServiceCategory)

	if err != nil {
		return err
	}

	*o = ResolvedServiceCategory(varResolvedServiceCategory)

	return err
}

type NullableResolvedServiceCategory struct {
	value *ResolvedServiceCategory
	isSet bool
}

func (v NullableResolvedServiceCategory) Get() *ResolvedServiceCategory {
	return v.value
}

func (v *NullableResolvedServiceCategory) Set(val *ResolvedServiceCategory) {
	v.value = val
	v.isSet = true
}

func (v NullableResolvedServiceCategory) IsSet() bool {
	return v.isSet
}

func (v *NullableResolvedServiceCategory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResolvedServiceCategory(val *ResolvedServiceCategory) *NullableResolvedServiceCategory {
	return &NullableResolvedServiceCategory{value: val, isSet: true}
}

func (v NullableResolvedServiceCategory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResolvedServiceCategory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


