/*
GoCommerce

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ConfigFeaturesContent struct for ConfigFeaturesContent
type ConfigFeaturesContent struct {
	Enabled bool `json:"enabled"`
}

// NewConfigFeaturesContent instantiates a new ConfigFeaturesContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigFeaturesContent(enabled bool) *ConfigFeaturesContent {
	this := ConfigFeaturesContent{}
	this.Enabled = enabled
	return &this
}

// NewConfigFeaturesContentWithDefaults instantiates a new ConfigFeaturesContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigFeaturesContentWithDefaults() *ConfigFeaturesContent {
	this := ConfigFeaturesContent{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *ConfigFeaturesContent) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *ConfigFeaturesContent) GetEnabledOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *ConfigFeaturesContent) SetEnabled(v bool) {
	o.Enabled = v
}

func (o ConfigFeaturesContent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["enabled"] = o.Enabled
	}
	return json.Marshal(toSerialize)
}

type NullableConfigFeaturesContent struct {
	value *ConfigFeaturesContent
	isSet bool
}

func (v NullableConfigFeaturesContent) Get() *ConfigFeaturesContent {
	return v.value
}

func (v *NullableConfigFeaturesContent) Set(val *ConfigFeaturesContent) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigFeaturesContent) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigFeaturesContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigFeaturesContent(val *ConfigFeaturesContent) *NullableConfigFeaturesContent {
	return &NullableConfigFeaturesContent{value: val, isSet: true}
}

func (v NullableConfigFeaturesContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigFeaturesContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


