/*
GoCommerce

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServiceCategory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceCategory{}

// ServiceCategory struct for ServiceCategory
type ServiceCategory struct {
	// Compressed representation of ID
	Id string `json:"id"`
	Name string `json:"name"`
	// Should be sorted ascending by this column
	Order int64 `json:"order"`
}

type _ServiceCategory ServiceCategory

// NewServiceCategory instantiates a new ServiceCategory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceCategory(id string, name string, order int64) *ServiceCategory {
	this := ServiceCategory{}
	this.Id = id
	this.Name = name
	this.Order = order
	return &this
}

// NewServiceCategoryWithDefaults instantiates a new ServiceCategory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceCategoryWithDefaults() *ServiceCategory {
	this := ServiceCategory{}
	return &this
}

// GetId returns the Id field value
func (o *ServiceCategory) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ServiceCategory) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ServiceCategory) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ServiceCategory) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ServiceCategory) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ServiceCategory) SetName(v string) {
	o.Name = v
}

// GetOrder returns the Order field value
func (o *ServiceCategory) GetOrder() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Order
}

// GetOrderOk returns a tuple with the Order field value
// and a boolean to check if the value has been set.
func (o *ServiceCategory) GetOrderOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Order, true
}

// SetOrder sets field value
func (o *ServiceCategory) SetOrder(v int64) {
	o.Order = v
}

func (o ServiceCategory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceCategory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["order"] = o.Order
	return toSerialize, nil
}

func (o *ServiceCategory) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"order",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServiceCategory := _ServiceCategory{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServiceCategory)

	if err != nil {
		return err
	}

	*o = ServiceCategory(varServiceCategory)

	return err
}

type NullableServiceCategory struct {
	value *ServiceCategory
	isSet bool
}

func (v NullableServiceCategory) Get() *ServiceCategory {
	return v.value
}

func (v *NullableServiceCategory) Set(val *ServiceCategory) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceCategory) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceCategory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceCategory(val *ServiceCategory) *NullableServiceCategory {
	return &NullableServiceCategory{value: val, isSet: true}
}

func (v NullableServiceCategory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceCategory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


