// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	imageproxy "github.com/JenswBE/go-commerce/utils/imageproxy"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GenerateURL provides a mock function with given fields: sourceURL, config
func (_m *Service) GenerateURL(sourceURL string, config imageproxy.ImageConfig) (string, error) {
	ret := _m.Called(sourceURL, config)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, imageproxy.ImageConfig) string); ok {
		r0 = rf(sourceURL, config)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, imageproxy.ImageConfig) error); ok {
		r1 = rf(sourceURL, config)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
