openapi: "3.0.2"
info:
  title: GoCommerce
  version: "1.0"

servers:
  - description: Local
    url: /api

paths:
  /public/categories/:
    get:
      operationId: public_list_categories
      description: List categories
      tags: ["Categories"]
      security: []
      parameters:
        - $ref: "#/components/parameters/queryImg"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryList"

  /public/categories/{id}/:
    parameters:
      - $ref: "#/components/parameters/pathID"
    get:
      operationId: public_get_category
      description: Get category details
      tags: ["Categories"]
      security: []
      parameters:
        - $ref: "#/components/parameters/queryImg"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"

  /admin/categories/:
    get:
      operationId: admin_list_categories
      description: List categories
      tags: ["Categories"]
      parameters:
        - $ref: "#/components/parameters/queryImg"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryList"
    post:
      operationId: admin_add_category
      description: Add category
      tags: ["Categories"]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"

  /admin/categories/{id}/:
    parameters:
      - $ref: "#/components/parameters/pathID"
    get:
      operationId: admin_get_category
      description: Get category details
      tags: ["Categories"]
      parameters:
        - $ref: "#/components/parameters/queryImg"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
    put:
      operationId: admin_update_category
      description: Update category
      tags: ["Categories"]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
    delete:
      operationId: admin_delete_category
      description: Delete category
      tags: ["Categories"]
      responses:
        "204":
          description: No Content

  /admin/categories/{id}/image/:
    parameters:
      - $ref: "#/components/parameters/pathID"
    put:
      operationId: admin_upsert_category_image
      description: Upsert image
      tags: ["Categories"]
      parameters:
        - $ref: "#/components/parameters/queryImg"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"
    delete:
      operationId: admin_delete_category_image
      description: Delete image
      tags: ["Categories"]
      responses:
        "204":
          description: No Content

  /public/manufacturers/:
    get:
      operationId: public_list_manufacturers
      description: List manufacturers
      tags: ["Manufacturers"]
      security: []
      parameters:
        - $ref: "#/components/parameters/queryImg"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ManufacturerList"

  /public/manufacturers/{id}/:
    parameters:
      - $ref: "#/components/parameters/pathID"
    get:
      operationId: public_get_manufacturer
      description: Get manufacturer details
      tags: ["Manufacturers"]
      security: []
      parameters:
        - $ref: "#/components/parameters/queryImg"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Manufacturer"

  /admin/manufacturers/:
    get:
      operationId: admin_list_manufacturers
      description: List manufacturers
      tags: ["Manufacturers"]
      parameters:
        - $ref: "#/components/parameters/queryImg"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ManufacturerList"
    post:
      operationId: admin_add_manufacturer
      description: Add manufacturer
      tags: ["Manufacturers"]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Manufacturer"
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Manufacturer"

  /admin/manufacturers/{id}/:
    parameters:
      - $ref: "#/components/parameters/pathID"
    get:
      operationId: admin_get_manufacturer
      description: Get manufacturer details
      tags: ["Manufacturers"]
      parameters:
        - $ref: "#/components/parameters/queryImg"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Manufacturer"
    put:
      operationId: admin_update_manufacturer
      description: Update manufacturer
      tags: ["Manufacturers"]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Manufacturer"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Manufacturer"
    delete:
      operationId: admin_delete_manufacturer
      description: Delete manufacturer
      tags: ["Manufacturers"]
      responses:
        "204":
          description: No Content

  /admin/manufacturers/{id}/image/:
    parameters:
      - $ref: "#/components/parameters/pathID"
    put:
      operationId: admin_upsert_manufacturer_image
      description: Upsert image
      tags: ["Manufacturers"]
      parameters:
        - $ref: "#/components/parameters/queryImg"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"
    delete:
      operationId: admin_delete_manufacturer_image
      description: Delete image
      tags: ["Manufacturers"]
      responses:
        "204":
          description: No Content

  /public/products/:
    get:
      operationId: public_list_products
      description: List products
      tags: ["Products"]
      security: []
      parameters:
        - $ref: "#/components/parameters/queryImg"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductList"

  /public/products/{id}/:
    parameters:
      - $ref: "#/components/parameters/pathID"
    get:
      operationId: public_get_product
      description: Get product details
      tags: ["Products"]
      security: []
      parameters:
        - $ref: "#/components/parameters/queryImg"
        - $ref: "#/components/parameters/resolve"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResolvedProduct"

  /admin/products/:
    get:
      operationId: admin_list_products
      description: List products
      tags: ["Products"]
      parameters:
        - $ref: "#/components/parameters/queryImg"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductList"
    post:
      operationId: admin_add_product
      description: Add product
      tags: ["Products"]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"

  /admin/products/{id}/:
    parameters:
      - $ref: "#/components/parameters/pathID"
    get:
      operationId: admin_get_product
      description: Get product details
      tags: ["Products"]
      parameters:
        - $ref: "#/components/parameters/queryImg"
        - $ref: "#/components/parameters/resolve"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResolvedProduct"
    put:
      operationId: admin_update_product
      description: Update product
      tags: ["Products"]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
    delete:
      operationId: admin_delete_product
      description: Delete product
      tags: ["Products"]
      responses:
        "204":
          description: No Content

  /admin/products/{id}/images/:
    parameters:
      - $ref: "#/components/parameters/pathID"
      - $ref: "#/components/parameters/queryImg"
    get:
      operationId: admin_list_product_images
      description: Get product images
      tags: ["Products"]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImageList"
    post:
      operationId: admin_add_product_images
      description: Add product images
      tags: ["Products"]
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                file:
                  type: array
                  items:
                    type: string
                    format: binary
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImageList"

  /admin/products/{id}/images/{image_id}/:
    parameters:
      - $ref: "#/components/parameters/pathID"
      - $ref: "#/components/parameters/pathImageID"
    put:
      operationId: admin_update_product_image
      description: >-
        Update product image.
        In case the new order matches another image, the orders are swapped.
        Therefore, this call will return all impacted images (1 or 2).
        First the image on which the request was called and optionally second the swapped image.
      tags: ["Products"]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Image"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImageList"
    delete:
      operationId: admin_delete_product_image
      description: Delete product image
      tags: ["Products"]
      responses:
        "204":
          description: No Content

components:
  parameters:
    pathID:
      name: id
      in: path
      description: ID
      required: true
      schema:
        $ref: "#/components/schemas/ShortID"

    pathImageID:
      name: image_id
      in: path
      description: Image ID
      required: true
      schema:
        $ref: "#/components/schemas/ShortID"

    queryImg:
      name: img
      in: query
      description: >-
        Comma separated list of ImageConfig.
        Check ImageConfig for exact format.
      required: false
      schema:
        type: array
        items:
          $ref: "#/components/schemas/ImageConfig"
      explode: false

    resolve:
      name: resolve
      in: query
      description: The returned object should include related objects.
      schema:
        type: boolean
        default: false

  schemas:
    Category:
      allOf:
        - $ref: "#/components/schemas/Header"
        - type: object
          properties:
            name:
              type: string
              example: Makeup & Cosmetica
            description:
              type: string
            parent_id:
              $ref: "#/components/schemas/ShortID"
            order:
              description: Should be sorted ascending by this column
              type: integer
              format: int64
            product_ids:
              type: array
              items:
                type: string
                format: uuid
              readOnly: True
            image_urls:
              $ref: "#/components/schemas/ImageUrlMap"
          required:
            - name
            - order

    CategoryList:
      type: object
      required:
        - categories
      properties:
        categories:
          type: array
          items:
            $ref: "#/components/schemas/Category"

    Header:
      type: object
      properties:
        id:
          type: string
          description: Compressed representation of ID
          example: "AneTxNh7GB5uD2HoXvwF2E"
          readOnly: True

    HeaderTimestamped:
      allOf:
        - $ref: "#/components/schemas/Header"
        - type: object
          properties:
            created_at:
              type: string
              format: date-time
              example: "2020-12-23T10:00:00Z"
              readOnly: True
            updated_at:
              type: string
              format: date-time
              example: "2020-12-24T11:30:00Z"
              readOnly: True

    Image:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        ext:
          type: string
          description: Extension of the image
          example: png
          readOnly: true
        urls:
          $ref: "#/components/schemas/ImageUrlMap"
        order:
          description: Should be sorted ascending by this column
          type: integer
          format: int64
      required:
        - id
        - ext
        - urls
        - order

    ImageConfig:
      type: string
      example: 300_200_FIT
      description: |-
        Comma separated list of image configs in format width_height_resizeMode.
        - Width: Width of the image
        - Height: Height of the image (optional, default = Width)
        - Resize mode (optional, default = FIT):
          - FIT:  Fits the image within the dimensions. Resulting image
                  might be smaller than dimensions.
          - FILL: Fill the dimensions with the image. Image might be cropped.

    ImageUrl:
      type: string
      description: Signed URL pointing to the image
      example: "https://images.jensw.be/.../fill/300/200/.../anBn.png"
      readOnly: true

    ImageUrlMap:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/ImageUrl"
      example:
        300_200_FIT: "https://images.jensw.be/.../fill/300/200/.../anBn.png"
      readOnly: true

    ImageList:
      type: object
      required:
        - images
      properties:
        images:
          type: array
          items:
            $ref: "#/components/schemas/Image"
      readOnly: true

    Manufacturer:
      required:
        - name
      allOf:
        - $ref: "#/components/schemas/Header"
        - type: object
          properties:
            name:
              type: string
              example: Bjoetiek Y
            website_url:
              type: string
              format: url
              example: https://bjoetiek-y.be
            image_urls:
              $ref: "#/components/schemas/ImageUrlMap"

    ManufacturerList:
      type: object
      required:
        - manufacturers
      properties:
        manufacturers:
          type: array
          items:
            $ref: "#/components/schemas/Manufacturer"

    Product:
      allOf:
        - $ref: "#/components/schemas/HeaderTimestamped"
        - type: object
          properties:
            name:
              type: string
              example: Gezichtsmasker
            description_short:
              type: string
            description_long:
              type: string
            price:
              description: Price in cents
              type: integer
              format: int64
              example: 1500
            category_ids:
              type: array
              items:
                type: string
                format: uuid
            manufacturer_id:
              type: string
              format: uuid
            status:
              $ref: "#/components/schemas/ProductStatus"
            stock_count:
              type: integer
              format: int64
            image_urls:
              type: array
              items:
                $ref: "#/components/schemas/ImageUrlMap"
              readOnly: true
          required:
            - name
            - price

    ProductStatus:
      type: string
      enum:
        - AVAILABLE
        - ARCHIVED

    ResolvedProduct:
      allOf:
        - $ref: "#/components/schemas/Product"
        - type: object
          properties:
            manufacturer:
              $ref: "#/components/schemas/Manufacturer"
            categories:
              type: array
              items:
                $ref: "#/components/schemas/Category"

    ProductList:
      type: object
      required:
        - products
      properties:
        products:
          type: array
          items:
            $ref: "#/components/schemas/Product"

    ShortID:
      type: string
      description: Compressed representation of ID
      example: "AneTxNh7GB5uD2HoXvwF2E"

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

security:
  - basicAuth: []
